python src_main.py 'data(TSP)/data-1.txt'
python src_main.py 'data(TSP)/data-5.txt'
python src_main.py 'data(TSP)/data-9.txt'
python src_main.py 'data(TSP)/data-13.txt'
python src_main.py 'data(TSP)/data-17.txt'
python src_main.py 'data(TSP)/data-21.txt'
python src_main.py 'data(TSP)/data-25.txt'
python src_main.py 'data(TSP)/data-29.txt'