#python src_main.py 'data(TSP)/data-2.txt'
#python src_main.py 'data(TSP)/data-6.txt'
#python src_main.py 'data(TSP)/data-10.txt'
#python src_main.py 'data(TSP)/data-14.txt'
python src_main.py 'data(TSP)/data-18.txt'
python src_main.py 'data(TSP)/data-22.txt'
python src_main.py 'data(TSP)/data-26.txt'
python src_main.py 'data(TSP)/data-30.txt'